version: '2.1'

services:
  elasticsearch:
    container_name: elasticsearch
    image: mwangxx/elasticsearch:7.6.0
    volumes:
      - /root/ws/BulletJournal/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - $HOME/docker/volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
  
  logstash:
    container_name: logstash
    image: mwangxx/logstash:7.6.0
    volumes:
      - /root/ws/BulletJournal/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /root/ws/BulletJournal/elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "127.0.0.1:5000:5000/tcp"
      - "127.0.0.1:5000:5000/udp"
      - "127.0.0.1:9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
      postgres_hostname: db
      postgres_jdbc_driver_absolute_path: /usr/share/logstash/logstash-core/lib/jars/postgresql.jar
      logstash_last_run_metadata_absolute_path: /usr/share/logstash/.logstash_jdbc_last_run
      elasticsearch_hostname: elasticsearch
    depends_on:
      - elasticsearch
